### ISSUE TITLE
Capture opens firefox

### ISSUE THREAD

**Issue by rsuhada** [CestDiego/org-capture-chrome#2]
Hi Diego,

I liked your blog about org-capture and I'm trying to get it running. My setup is very similar to yours - I also use i3 and I followed the instructions.

When I hit C-S-l in Chromium however, firefox opens and asks me which application I want to open the org-protocol with. Even if I select emacs-capture, nothing else happens.

emacs-capture is in my path. I think this is some sort of mix-up with the mimetype opener, but can't figure it out. My i3 is running on top of xubuntu, but the `$XDG_CURRENT_DESKTOP` is correctly "i3", and running 

    xdg-mime query default x-scheme-handler/org-protocol

gives correctly `emacs-capture.desktop`...

Do you have an idea what could be wrong here? 
Thank you!

**Comment by CestDiego** [comment]
Hi. I remember this happening to me for a while... Can you double check if chromium is your default browser for all mimetypes? Also could you put the absolute path in the .desktop file and try again? I haven't had a Linux machine for a while so my knowledge of this is a little foggy

**Comment by rsuhada** [comment]
I've just figured it out - emacsclient wasn't running (not sure why firefox took over though I remved it from everywhere...). After starting the server the extension works! Thanks!
