### ISSUE TITLE
Extension does not always pass url to xdg-open

### ISSUE THREAD

**Issue by franburstall** [CestDiego/org-capture-chrome#3]
When firing the Ultimate Org Capture extension either by key-stroke or from the button, the extension creates the correct org-protocol url (as evidenced by console.log) but sometimes does not try to open it so that no emacs window is opened.

If I copy the url into the address bar and open it then the url is passed to xdg-open as expected and everything works (the little emacs frame opens with a capture template filled out correctly and so on).

The effect seems to depend on the source web-page.  For example:

http://www.diegoberrocal.com/blog/2015/08/19/org-protocol/ works fine but

http://orgmode.org/worg/org-contrib/org-protocol.html#sec-9 (and many others) does not.

Any ideas?

This is with chromium Version 55.0.2883.75 under Linux Mint Debian Edition 2.

**Comment by robaczek** [comment]
Can confirm behavior described above.
